version: "3.8"
services:
  db:
    image: "postgres:12.3-alpine"
    container_name: shop-db
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
#    ports:
#      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: "nginx:1.19.1-alpine"
    container_name: shop-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_data:/static
      - media_data:/media
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/nginx/certs/server.crt
      - ./server.key:/etc/nginx/certs/server.key
    depends_on:
      - web
  web:
    container_name: shop-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 -w 3 --reload --error-logfile - --log-level debug
#    ports:
#      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=shop
      - DEBUG=True
    volumes:
      - ./src:/app
      - static_data:/static
      - media_data:/media
    depends_on:
      - db

volumes:
  postgres_data:
  static_data:
  media_data:
